version: '3.8'

services:
  app:
    build:
      context: .             
      dockerfile: Dockerfile  
    container_name: bigdataimporter_app
    ports:
      - "8080:8080"             
    volumes:
      - ./uploads:/app/uploads  
      - ./logs:/app/logs         
      - ./results:/app/results  
    restart: unless-stopped
